import pymysql
import pandas as pd
import matplotlib.pyplot as plt
import koreanize_matplotlib
import numpy as np
conn=pymysql.connect(host='172.20.54.245', user='member2', password='1234', db='fuel', charset='utf8')
cur = conn.cursor(pymysql.cursors.DictCursor)
cur.execute('select	* from f_bsi')
rows = cur.fetchall()
f_bsi_df = pd.DataFrame(rows)
print(f_bsi_df)
f_bsi_df=f_bsi_df.set_index(['년도'])
price_fuel=f_bsi_df.loc[:, ['고급휘발유','보통휘발유','자동차용경유']]
industries=f_bsi_df.loc[:, ['전체산업','대기업','서비스업','중소기업','비제조업','중화학공업','경공업','수출기업','내수기업']]
print(price_fuel)
print(industries)
print(price_fuel.index)
plt.figure()
plt.rc('font', size=20)
plt.rc('axes', labelsize=20)
plt.rc('xtick', labelsize=10)
plt.rc('ytick', labelsize=10)
plt.rc('legend', fontsize=20)
plt.rc('figure', titlesize=50)
plt.plot(price_fuel,'o-')
plt.xlabel('연도별',fontsize=20)
plt.ylabel('물가지수',fontsize=20)
plt.legend(price_fuel,loc='upper right',bbox_to_anchor=(1.28, 1), fontsize=20)
plt.xticks([2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023])
plt.title('연도별 기름값 변동')
plt.grid(True)
plt.tight_layout()
plt.show()
plt.figure()
plt.rc('font', size=20)
plt.rc('axes', labelsize=20)
plt.rc('xtick', labelsize=10)
plt.rc('ytick', labelsize=10)
plt.rc('legend', fontsize=20)
plt.rc('figure', titlesize=50)
plt.plot(industries,'o-')
plt.xlabel('연도별',fontsize=20)
plt.ylabel('업종별',fontsize=20)
plt.legend(industries,loc='upper right',bbox_to_anchor=(1.25, 1), fontsize=20)
plt.xticks([2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023])
plt.title('기업경기실사지수')
plt.grid(True)
plt.tight_layout()
plt.show()
cur.close()
conn.close()